# Generated by Django 4.0.10 on 2023-07-18 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=10000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('judge', models.CharField(choices=[(1, 'Python 2.7.18'), (2, 'Python 3.8.10'), (3, 'GNU GCC C11 11.2.0'), (4, 'GNU G++14 11.2.0')], max_length=30)),
                ('verdict', models.CharField(choices=[('AC', 'accepted'), ('WA', 'wrong answer'), ('TE', 'time limit exceeded'), ('CE', 'compile error'), ('RE', 'runtime error'), ('TT', 'testing')], default='TT', max_length=2)),
                ('time', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
